version: '3.7'

services:
    lesson75_docker:
        image: api_docker_image
        container_name: api_container
        ports:  
            - "7777:80"
        build: 
            context: .
            dockerfile: Dockerfile
        networks:
            - api_network
        
    api_db:
        image: postgres:latest
        container_name: api_postgres_db
        environment: 
            - POSTGRES_PASSWORD=my_password
            - POSTGRES_User=my_username
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - api_volume:/var/lib/postgresql/data/
        networks:
            - api_network
    
networks:
    api_network:
        driver: bridge

volumes:
    api_volume:  